packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@google/genai': set this to true or false
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  protobufjs: set this to true or false
